"""initial migration

Revision ID: a101a46b4b23
Revises: 
Create Date: 2024-07-03 16:35:36.801322-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a101a46b4b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.Integer(), nullable=True),
    sa.Column('time_ping', sa.Integer(), nullable=True),
    sa.Column('time_birthday', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('auth_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=False)
    op.create_table('user_service',
    sa.Column('uuid', sa.String(length=56), nullable=False),
    sa.Column('user_uuid', sa.String(length=56), nullable=True),
    sa.Column('client_uuid', sa.String(length=56), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_personal', sa.Boolean(), nullable=True),
    sa.Column('service_type', sa.String(length=56), nullable=True),
    sa.Column('service_user_id', sa.String(length=255), nullable=True),
    sa.Column('service_user_screenname', sa.String(length=255), nullable=True),
    sa.Column('service_user_name', sa.String(length=255), nullable=True),
    sa.Column('service_access_token', sa.String(length=255), nullable=True),
    sa.Column('service_access_secret', sa.String(length=255), nullable=True),
    sa.Column('service_refresh_token', sa.String(length=255), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.Integer(), nullable=True),
    sa.Column('login_secret', sa.String(length=255), nullable=True),
    sa.Column('login_token', sa.String(length=56), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_service_client_uuid'), 'user_service', ['client_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_service_client_uuid'), table_name='user_service')
    op.drop_table('user_service')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
