
# docker push docker push magic_signon/localstack:latest

FROM localstack/localstack:latest
COPY Docker/localstack_ready.sh /etc/localstack/init/ready.d/ready.sh
RUN chmod +x /etc/localstack/init/ready.d/ready.sh
